#!/bin/sh

v4l2-ctl --set-fmt-video=width=1280,height=720,pixelformat=1
v4l2-ctl --verbose --set-ctrl=exposure_auto_priority=0
v4l2-ctl --verbose --set-ctrl=exposure_auto=3
v4l2-ctl --set-ctrl=white_balance_temperature_auto=0
v4l2-ctl --set-ctrl=exposure_auto_priority=0
v4l2-ctl --set-ctrl=backlight_compensation=0
v4l2-ctl --set-parm=30

./webcam

